import { Link, useNavigate } from "react-router-dom";
import { useMemo, useState } from "react";
import { Download, IndianRupee, Receipt, Search } from "lucide-react";
import { toast } from "sonner";

import { PageHeader } from "@/components/layout/page-header";
import { DataTable } from "@/components/common/data-table";
import { StatCard } from "@/components/common/stat-card";
import { DocStatusBadge } from "@/components/common/doc-common";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { clusterName, customers, docTotals, invoices } from "@/data/mock-data";
import { fmtDate, inr, inrShort } from "@/lib/format";
import { useScope } from "@/context/session-context";
import type { Invoice } from "@/types";

export function InvoicesPage() {
  const { scope, visibleClusters, role } = useScope();
  const navigate = useNavigate();

  const [query, setQuery] = useState("");
  const [statusFilter, setStatusFilter] = useState("all");
  const [clusterFilter, setClusterFilter] = useState("all");

  const scopedInvoices = useMemo(() => scope(invoices), [scope]);

  const filtered = useMemo(() => {
    return scopedInvoices.filter((i) => {
      if (query.trim()) {
        const text = query.toLowerCase();
        const customer = customers.find((c) => c.id === i.customerId);
        const match =
          i.id.toLowerCase().includes(text) ||
          (customer && customer.name.toLowerCase().includes(text));
        if (!match) return false;
      }
      if (statusFilter !== "all" && i.status !== statusFilter) return false;
      if (clusterFilter !== "all" && i.clusterId !== clusterFilter) return false;
      return true;
    });
  }, [scopedInvoices, query, statusFilter, clusterFilter]);

  const totalValue = scopedInvoices.reduce((s, i) => s + docTotals(i.items).total, 0);
  const totalPaid = scopedInvoices.reduce((s, i) => s + i.paid, 0);

  return (
    <div className="space-y-6">
      <PageHeader
        title="Tax Invoices"
        description="Final commercial GST tax invoices generated by clusters upon order dispatch."
        actions={
          <Button
            variant="outline"
            size="sm"
            onClick={() => toast.success("Exporting invoices to CSV")}
          >
            <Download className="size-4" /> Export CSV
          </Button>
        }
      />

      <div className="grid gap-4 sm:grid-cols-3">
        <StatCard
          label="Total Invoices"
          value={scopedInvoices.length}
          icon={Receipt}
          tone="brand"
        />
        <StatCard
          label="Total Invoiced Amount"
          value={inrShort(totalValue)}
          icon={IndianRupee}
          tone="teal"
        />
        <StatCard label="Collected Revenue" value={inrShort(totalPaid)} tone="default" />
      </div>

      <div className="card-elevated p-4">
        <div className="flex flex-wrap items-center gap-3">
          <div className="relative min-w-[220px] flex-1">
            <Search className="pointer-events-none absolute top-1/2 left-3 size-4 -translate-y-1/2 text-muted-foreground" />
            <Input
              placeholder="Search by invoice ID or customer name…"
              value={query}
              onChange={(e) => setQuery(e.target.value)}
              className="pl-9"
            />
          </div>

          <Select value={statusFilter} onValueChange={setStatusFilter}>
            <SelectTrigger className="w-36 bg-card">
              <SelectValue placeholder="Status" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">All Statuses</SelectItem>
              {["Paid", "Partially Paid", "Pending", "Issued", "Cancelled"].map((s) => (
                <SelectItem key={s} value={s}>
                  {s}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>

          {role !== "cluster" && (
            <Select value={clusterFilter} onValueChange={setClusterFilter}>
              <SelectTrigger className="w-44 bg-card">
                <SelectValue placeholder="Cluster" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">All Clusters</SelectItem>
                {visibleClusters.map((c) => (
                  <SelectItem key={c.id} value={c.id}>
                    {c.name}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          )}
        </div>
      </div>

      <DataTable
        columns={[
          {
            key: "id",
            header: "Invoice ID",
            cell: (r) => (
              <Link to={`/invoices/${r.id}`} className="font-semibold text-primary hover:underline">
                {r.id}
              </Link>
            ),
          },
          {
            key: "customer",
            header: "Customer",
            cell: (r) => {
              const cust = customers.find((c) => c.id === r.customerId);
              return cust ? cust.name : r.customerId;
            },
          },
          { key: "cluster", header: "Cluster", cell: (r) => clusterName(r.clusterId) },
          {
            key: "total",
            header: "Total Amount",
            cell: (r) => <span className="font-semibold">{inr(docTotals(r.items).total)}</span>,
          },
          {
            key: "paid",
            header: "Paid",
            cell: (r) => <span className="text-primary font-medium">{inr(r.paid)}</span>,
          },
          { key: "status", header: "Status", cell: (r) => <DocStatusBadge status={r.status} /> },
          { key: "date", header: "Date", cell: (r) => fmtDate(r.date) },
          { key: "dueDate", header: "Due Date", cell: (r) => fmtDate(r.dueDate) },
        ]}
        rows={filtered}
        onRowClick={(r) => navigate(`/invoices/${r.id}`)}
      />
    </div>
  );
}
